export const menuArray = [
  {
    id: 0,
    price: 14,
    name: "Pepproni Pizza",
    type: "pizza",
    ingredients: ["pepperoni", "mushrom", "mozarella"],
  },
  {
    id: 1,
    price: 12,
    name: "Hamburger",
    type: "burgers",
    ingredients: ["beef", "cheese", "lettuce"],
  },
  {
    id: 2,
    price: 12,
    name: "Beer",
    type: "drinks",
    ingredients: ["grain, hops, yeast, water"],
  },
  {
    id: 3,
    price: 1.99,
    name: "Coca-Cola",
    type: "drinks",
    ingredients: ["coca-cola, ice"],
  },
  {
    id: 4,
    price: 3.99,
    name: "French Fries",
    type: "sides",
    ingredients: ["potatoes, Vegetable Oil, Dextrose"],
  },
  {
    id: 5,
    price: 6.99,
    name: "Lava cake",
    type: "sides",
    ingredients: ["chocolate, butter, sugar, eggs"],
  },
  {
    id: 6,
    price: 12,
    name: "Cheese Pizza",
    type: "pizza",
    ingredients: ["mozarella"],
  },
  {
    id: 7,
    price: 10.99,
    name: "Veggie Burger",
    type: "burgers",
    ingredients: ["red onions", "fresh baby spinach", "veggie patti"],
  },
  {
    id: 8,
    price: 14.99,
    name: "Chicken Burger",
    type: "burgers",
    ingredients: ["ground chicken", "whole wheat", "cucumber", "lettuce"],
  },
  {
    id: 9,
    price: 5.99,
    name: "Apple Juice",
    type: "drinks",
    ingredients: ["apples, cinnamon, sugar"],
  },
  {
    id: 10,
    price: 5.99,
    name: "Orange Juice",
    type: "drinks",
    ingredients: ["orange juice concentrate, filtered water"],
  },
  {
    id: 11,
    price: 6.99,
    name: "Lemonade",
    type: "drinks",
    ingredients: ["lemon juice, filtered water, cane sugar"],
  },
  {
    id: 12,
    price: 1.99,
    name: "Orange Crush",
    type: "drinks",
    ingredients: ["orange flavored vodka, triple sec, cane sugar"],
  },
];
