export const menuArray = [
  {
    id: 0,
    emoji: "🍕",
    price: 14,
    name: "Pepproni Pizza",
    type: "pizza",
    ingredients: ["pepperoni", "mushrom", "mozarella"],
  },
  {
    id: 1,
    emoji: "🍔",
    price: 12,
    name: "Hamburger",
    type: "burgers",
    ingredients: ["beef", "cheese", "lettuce"],
  },
  {
    id: 2,
    emoji: "🍺",
    price: 12,
    name: "Beer",
    type: "drinks",
    ingredients: ["grain, hops, yeast, water"],
  },
  {
    id: 3,
    emoji: "🥤",
    price: 1.99,
    name: "Coca-Cola",
    type: "drinks",
    ingredients: ["coca-cola, ice"],
  },
  {
    id: 4,
    emoji: "🍟",
    price: 3.99,
    name: "French Fries",
    type: "sides",
    ingredients: ["potatoes, Vegetable Oil, Dextrose"],
  },
  {
    id: 5,
    emoji: "🍰",
    price: 6.99,
    name: "Lava cake",
    type: "sides",
    ingredients: ["chocolate, butter, sugar, eggs"],
  },
  {
    id: 6,
    emoji: "🍕",
    price: 12,
    name: "Cheese Pizza",
    type: "pizza",
    ingredients: ["mozarella"],
  },
  {
    id: 7,
    emoji: "🍔",
    price: 12,
    name: "Veggie Burger",
    type: "burgers",
    ingredients: ["red onions", "fresh baby spinach", "veggie patti"],
  },
];
