import { v4 as uuidv4 } from "https://jspm.dev/uuid";

export const foodMenu = [
  {
    id: uuidv4(),
    price: 14.99,
    name: "Pepproni Pizza",
    type: "pizza",
    ingredients: ["pepperoni", "mushrom", "mozarella"],
  },
  {
    id: uuidv4(),
    price: 12.99,
    name: "Hamburger",
    type: "burgers",
    ingredients: ["beef", "cheese", "lettuce"],
  },
  {
    id: uuidv4(),
    price: 12.99,
    name: "Beer",
    type: "drinks",
    ingredients: ["grain, hops, yeast, water"],
  },
  {
    id: uuidv4(),
    price: 1.99,
    name: "Coca-Cola",
    type: "drinks",
    ingredients: ["coca-cola, ice"],
  },
  {
    id: uuidv4(),
    price: 3.99,
    name: "French Fries",
    type: "sides",
    ingredients: ["potatoes, Vegetable Oil, Dextrose"],
  },
  {
    id: uuidv4(),
    price: 6.99,
    name: "Lava cake",
    type: "sides",
    ingredients: ["chocolate, butter, sugar, eggs"],
  },
  {
    id: uuidv4(),
    price: 10.99,
    name: "Cheese Pizza",
    type: "pizza",
    ingredients: ["mozarella"],
  },
  {
    id: uuidv4(),
    price: 10.99,
    name: "Veggie Burger",
    type: "burgers",
    ingredients: ["red onions", "fresh baby spinach", "veggie patti"],
  },
  {
    id: uuidv4(),
    price: 14.99,
    name: "Chicken Burger",
    type: "burgers",
    ingredients: ["ground chicken", "whole wheat", "cucumber", "lettuce"],
  },
  {
    id: uuidv4(),
    price: 5.99,
    name: "Apple Juice",
    type: "drinks",
    ingredients: ["apples, cinnamon, sugar"],
  },
  {
    id: uuidv4(),
    price: 5.99,
    name: "Orange Juice",
    type: "drinks",
    ingredients: ["orange juice concentrate, filtered water"],
  },
  {
    id: uuidv4(),
    price: 6.99,
    name: "Lemonade",
    type: "drinks",
    ingredients: ["lemon juice, filtered water, cane sugar"],
  },
  {
    id: uuidv4(),
    price: 1.99,
    name: "Orange Crush",
    type: "drinks",
    ingredients: ["orange flavored vodka, triple sec, cane sugar"],
  },
  {
    id: uuidv4(),
    price: 6.99,
    name: "Garlic Bread with Cheese",
    type: "sides",
    ingredients: ["mozzarella cheese, italian bread, parmesan cheese"],
  },
  {
    id: uuidv4(),
    price: 6.99,
    name: "Garlic Sticks",
    type: "sides",
    ingredients: ["bread flour, mozzarella cheese, parmesan cheese"],
  },
  {
    id: uuidv4(),
    price: 5.99,
    name: "Onion Rings",
    type: "sides",
    ingredients: ["bread crumbs, egg, baking powder, seasoned salt,"],
  },
  {
    id: uuidv4(),
    price: 6.99,
    name: "Mozzarella Sticks",
    type: "sides",
    ingredients: [
      "part-skim mozzarella cheese, wheat flour, soybean oil, water",
    ],
  },
  {
    id: uuidv4(),
    price: 15.69,
    name: "Canadian Veggie Pizza",
    type: "pizza",
    ingredients: ["green pepper, tomatoes, mushrooms & green olives"],
  },
  {
    id: uuidv4(),
    price: 16.99,
    name: "Spicy Italian Pizza",
    type: "pizza",
    ingredients: ["thin crust, hot italian sausage, ham & roasted red peppers"],
  },
  {
    id: uuidv4(),
    price: 15.99,
    name: "Mexican Pizza",
    type: "pizza",
    ingredients: ["ground beef, tomatoes, onions & jalapeno peppers"],
  },
  {
    id: uuidv4(),
    price: 14.99,
    name: "Hawaiian Pizza",
    type: "pizza",
    ingredients: ["ham, pineapple & extra cheese"],
  },
  {
    id: uuidv4(),
    price: 15.69,
    name: "Greek Pizza",
    type: "pizza",
    ingredients: ["black olives, sliced tomatoes, onions & Feta cheese"],
  },
];
